name: update-cv
on:
  push:
    branches:
      - main
jobs:
  build-cv:
    runs-on: ubuntu-20.04
    name: build PDF
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: run script
        run: chmod +x gen_pdf.sh && sh gen_pdf.sh
      - name: upload pdf
        uses: actions/upload-artifact@v4
        with:
          name: cv
          path: src/main.pdf
          retention-days: 1
  publish-cv:
    needs: build-cv
    runs-on: ubuntu-20.04
    name: update PDF on pages
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
        with:
          ref: artifact
      - name: acquire cv
        uses: actions/download-artifact@v4
        with:
          name: cv
      - name: upload cv to pages
        run: |
          git config user.name 'Ischenko Alexis'
          git config user.email 'ishhenko.as@phystech.edu'
          git add main.pdf
          git commit -m "Upload new CV version"
          git push origin artifact
